steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/atbash-sandbox:latest"
      - "--build-arg"
      - "ATBASH_CLI_VERSION=latest"
      - "."
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/atbash-sandbox:latest"]

images:
  - "gcr.io/$PROJECT_ID/atbash-sandbox:latest"

options:
  logging: CLOUD_LOGGING_ONLY
